# Generated by Django 5.0.3 on 2024-04-20 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="User_Info",
            fields=[
                (
                    "User_Id",
                    models.CharField(max_length=50, primary_key=True, serialize=False),
                ),
                ("User_Name", models.CharField(max_length=100)),
                ("User_Address", models.CharField(max_length=200)),
                ("User_contact_N0", models.CharField(max_length=15, null=True)),
                ("User_Email_Id", models.CharField(max_length=30, null=True)),
                ("Branch_CD", models.IntegerField()),
            ],
        ),
    ]
