# Generated by Django 5.0.3 on 2024-04-20 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("packetTrackingSystem", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="POD_Records",
            fields=[
                (
                    "AWBNO",
                    models.CharField(max_length=10, primary_key=True, serialize=False),
                ),
                ("Del_Status", models.CharField(max_length=20)),
                ("Reciever_Name", models.CharField(max_length=100)),
                ("Reciever_Contact_No", models.CharField(max_length=15, null=True)),
                ("RTO_Reason", models.CharField(max_length=30, null=True)),
                ("Relation", models.CharField(max_length=50, null=True)),
                ("Attempt_Date", models.DateTimeField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name="printOption",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Branch_CD", models.IntegerField()),
                ("CurrentAWB", models.CharField(max_length=10)),
                ("Setting_CD", models.CharField(max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name="Rate_Plane_Details",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Planecode", models.CharField(max_length=10)),
                ("Description", models.CharField(max_length=255)),
            ],
        ),
    ]
