# Generated by Django 5.0.3 on 2024-04-21 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("packetTrackingSystem", "0002_pod_records_printoption_rate_plane_details"),
    ]

    operations = [
        migrations.CreateModel(
            name="Data_Records",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
            ],
        ),
    ]
