# Generated by Django 5.0.3 on 2024-04-26 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("packetTrackingSystem", "0002_alter_user_info_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user_info",
            name="Branch_CD",
            field=models.IntegerField(null=True),
        ),
    ]
