# Generated by Django 5.0.3 on 2024-04-27 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("packetTrackingSystem", "0003_alter_user_info_branch_cd"),
    ]

    operations = [
        migrations.AddField(
            model_name="pod_records",
            name="id",
            field=models.BigAutoField(
                auto_created=True,
                default=1,
                primary_key=True,
                serialize=False,
                verbose_name="ID",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="pod_records",
            name="AWBNO",
            field=models.CharField(max_length=10),
        ),
    ]
