# Generated by Django 5.0.3 on 2024-04-21 07:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("packetTrackingSystem", "0003_data_records"),
    ]

    operations = [
        migrations.RenameField(
            model_name="pod_records",
            old_name="Reciever_Contact_No",
            new_name="Receiver_Contact_No",
        ),
        migrations.RenameField(
            model_name="pod_records",
            old_name="Reciever_Name",
            new_name="Receiver_Name",
        ),
        migrations.RenameField(
            model_name="rate_plane_details",
            old_name="Planecode",
            new_name="Plan_code",
        ),
    ]
