# Generated by Django 5.0.3 on 2024-05-05 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("packetTrackingSystem", "0004_pod_records_id_alter_pod_records_awbno"),
    ]

    operations = [
        migrations.CreateModel(
            name="Qr_Details",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("barcode_image", models.ImageField(upload_to="qr_codes/")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
