# Generated by Django 5.0.3 on 2024-05-05 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("packetTrackingSystem", "0005_qr_details"),
    ]

    operations = [
        migrations.AddField(
            model_name="qr_details",
            name="awbno",
            field=models.CharField(default="", max_length=100),
            preserve_default=False,
        ),
    ]
