# Generated by Django 5.0.3 on 2024-05-05 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("packetTrackingSystem", "0006_qr_details_awbno"),
    ]

    operations = [
        migrations.CreateModel(
            name="Packet",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("AWBNO", models.CharField(max_length=50, unique=True)),
                (
                    "transit_status",
                    models.CharField(default="In Transit", max_length=100),
                ),
                ("last_update_time", models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
