# Generated by Django 5.0.3 on 2024-05-05 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("packetTrackingSystem", "0007_packet"),
    ]

    operations = [
        migrations.CreateModel(
            name="Order_Updates",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("AWBNO", models.CharField(max_length=50)),
                (
                    "transit_status",
                    models.CharField(default="In Transit", max_length=100),
                ),
                ("update_location", models.CharField(max_length=100)),
                ("last_update_time", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.DeleteModel(
            name="Packet",
        ),
    ]
