# Generated by Django 5.0.3 on 2024-05-05 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("packetTrackingSystem", "0009_order_updates_delivery_boy"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="order_updates",
            name="delivery_boy",
        ),
        migrations.AddField(
            model_name="order_updates",
            name="Delivery_Boy_Name",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="order_updates",
            name="last_update_time",
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name="order_updates",
            name="transit_status",
            field=models.CharField(
                default="Not Picked Up From Source.", max_length=100
            ),
        ),
    ]
