# Generated by Django 5.0.3 on 2024-05-05 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("packetTrackingSystem", "0010_remove_order_updates_delivery_boy_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Live_Updates",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("AWBNO", models.CharField(max_length=50)),
                (
                    "transit_status",
                    models.CharField(
                        default="Not Picked Up From Source.", max_length=100
                    ),
                ),
                ("update_location", models.CharField(max_length=100)),
                ("last_update_time", models.DateTimeField()),
                ("Delivery_Boy_Name", models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name="Order_Updates",
        ),
    ]
