# Generated by Django 5.0.3 on 2024-04-22 16:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("homeapp", "0002_login_info"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Login_Info",
        ),
    ]
