# Generated by Django 5.0.3 on 2024-05-07 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("homeapp", "0004_alter_feedback_feedback_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="feedback",
            name="Branch_Id",
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name="feedback",
            name="Branch_name",
            field=models.CharField(max_length=50, null=True),
        ),
    ]
