# Generated by Django 5.0.3 on 2024-04-21 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Branches",
            fields=[
                ("Branch_CD", models.IntegerField(primary_key=True, serialize=False)),
                ("Branch_NM", models.CharField(max_length=50)),
                ("countryId", models.IntegerField()),
                ("stateId", models.IntegerField()),
                ("cityId", models.IntegerField()),
                ("Address", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="delivery_Boy",
            fields=[
                (
                    "Delivery_Boy_Id",
                    models.CharField(max_length=10, primary_key=True, serialize=False),
                ),
                ("Delivery_Boy_Name", models.CharField(max_length=50)),
                ("Delivery_Boy_Address", models.CharField(max_length=100)),
                ("Delivery_Boy_contact_No", models.IntegerField()),
                ("Delivery_Boy_Area", models.CharField(max_length=30, null=True)),
                ("Branch_CD", models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="delivery_Boy_ID",
            fields=[
                (
                    "Current_ID",
                    models.CharField(max_length=4, primary_key=True, serialize=False),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PacketAssignmentDetails",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Delievery_Boy_Id", models.CharField(max_length=10)),
                ("AWBNO", models.CharField(max_length=50)),
                ("Assign_DT", models.DateTimeField()),
            ],
        ),
    ]
