# Generated by Django 5.0.3 on 2024-04-22 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "BranchesInfo",
            "0002_rename_delievery_boy_id_packetassignmentdetails_delivery_boy_id",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="delivery_boy",
            name="Delivery_Boy_Id",
            field=models.BigAutoField(max_length=10, primary_key=True, serialize=False),
        ),
    ]
