# Generated by Django 5.0.3 on 2024-04-26 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("BranchesInfo", "0003_alter_delivery_boy_delivery_boy_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="delivery_boy",
            name="Delivery_Boy_Id",
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
