# Generated by Django 5.0.3 on 2024-04-27 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("BranchesInfo", "0004_alter_delivery_boy_delivery_boy_id"),
    ]

    operations = [
        migrations.CreateModel(
            name="ChargeDetails",
            fields=[
                ("PlanCode", models.IntegerField(primary_key=True, serialize=False)),
                ("Distance", models.CharField(max_length=50)),
                ("Weight", models.CharField(max_length=10)),
                ("Amount", models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name="CityDetails",
            fields=[
                ("CityId", models.BigAutoField(primary_key=True, serialize=False)),
                ("stateId", models.ImageField(upload_to="")),
                ("CityName", models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name="Data_Records",
            fields=[
                (
                    "AWBNO",
                    models.CharField(max_length=10, primary_key=True, serialize=False),
                ),
                ("Sender_Name", models.CharField(max_length=100, null=True)),
                ("Sender_Address", models.CharField(max_length=100, null=True)),
                ("Sender_Contact_No", models.CharField(max_length=15, null=True)),
                ("Sender_City", models.CharField(max_length=30, null=True)),
                ("Receiver_Name", models.CharField(max_length=100)),
                ("Receiver_Contact_No", models.CharField(max_length=15, null=True)),
                ("Receiver_City", models.CharField(max_length=30, null=True)),
                ("Book_date", models.DateTimeField()),
                ("Weight", models.CharField(max_length=10, null=True)),
                ("Price", models.CharField(max_length=10, null=True)),
                ("POD_Flag", models.CharField(max_length=20, null=True)),
                ("Print_Flag", models.CharField(max_length=20, null=True)),
                ("Pin_Number", models.CharField(max_length=10, null=True)),
                ("State", models.CharField(max_length=30, null=True)),
                ("Country", models.CharField(max_length=30, null=True)),
                ("Sender_Branch_CD", models.IntegerField()),
                ("Receiver_Branch_CD", models.IntegerField()),
                ("Type", models.CharField(max_length=50, null=True)),
                ("Client_Id", models.CharField(max_length=50, null=True)),
                ("Alert_Flag", models.CharField(max_length=20, null=True)),
            ],
        ),
    ]
