# Generated by Django 5.0.3 on 2024-04-28 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("BranchesInfo", "0005_chargedetails_citydetails_data_records"),
    ]

    operations = [
        migrations.AddField(
            model_name="data_records",
            name="Receiver_Address",
            field=models.CharField(max_length=100, null=True),
        ),
    ]
