# Generated by Django 5.0.3 on 2024-04-28 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("BranchesInfo", "0006_data_records_receiver_address"),
    ]

    operations = [
        migrations.AddField(
            model_name="branches",
            name="Branch_head",
            field=models.CharField(max_length=100, null=True),
        ),
    ]
