# Generated by Django 5.0.3 on 2024-04-28 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("BranchesInfo", "0007_branches_branch_head"),
    ]

    operations = [
        migrations.RenameField(
            model_name="branches",
            old_name="Branch_head",
            new_name="city",
        ),
        migrations.AddField(
            model_name="branches",
            name="country",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="branches",
            name="state",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="branches",
            name="cityId",
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name="branches",
            name="countryId",
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name="branches",
            name="stateId",
            field=models.IntegerField(null=True),
        ),
    ]
