# Generated by Django 5.0.3 on 2024-04-28 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "BranchesInfo",
            "0008_rename_branch_head_branches_city_branches_country_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="branches",
            name="Branch_head",
            field=models.CharField(max_length=100, null=True),
        ),
    ]
