# Generated by Django 5.0.3 on 2024-04-28 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("BranchesInfo", "0009_branches_branch_head"),
    ]

    operations = [
        migrations.AlterField(
            model_name="branches",
            name="cityId",
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="branches",
            name="countryId",
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="branches",
            name="stateId",
            field=models.CharField(max_length=50, null=True),
        ),
    ]
