# Generated by Django 5.0.3 on 2024-04-28 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("BranchesInfo", "0011_branch_head"),
    ]

    operations = [
        migrations.CreateModel(
            name="delivery_Boy_details",
            fields=[
                (
                    "Delivery_Boy_Id",
                    models.BigAutoField(primary_key=True, serialize=False),
                ),
                ("Delivery_Boy_Name", models.CharField(max_length=50)),
                ("Delivery_Boy_Password", models.CharField(max_length=50)),
                ("Delivery_Boy_Address", models.CharField(max_length=100)),
                ("Delivery_Boy_contact_No", models.IntegerField()),
                ("Delivery_Boy_Area", models.CharField(max_length=30, null=True)),
                ("Branch_CD", models.IntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name="delivery_Boy",
        ),
    ]
