# Generated by Django 5.0.3 on 2024-04-28 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("BranchesInfo", "0012_delivery_boy_details_delete_delivery_boy"),
    ]

    operations = [
        migrations.AddField(
            model_name="branch_head",
            name="User_Type",
            field=models.CharField(default="", max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="delivery_boy_details",
            name="User_Type",
            field=models.CharField(default="", max_length=20),
            preserve_default=False,
        ),
    ]
