# Generated by Django 5.0.3 on 2024-04-28 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("BranchesInfo", "0013_branch_head_user_type_delivery_boy_details_user_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="delivery_boy_details",
            name="Delivery_Boy_Username",
            field=models.CharField(default="", max_length=50),
            preserve_default=False,
        ),
    ]
