# Generated by Django 5.0.3 on 2024-05-01 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "BranchesInfo",
            "0015_data_records_order_type_data_records_receiver_state_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="data_records",
            name="Receiver_Branch_CD",
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name="data_records",
            name="Sender_Branch_CD",
            field=models.IntegerField(null=True),
        ),
    ]
