# Generated by Django 5.0.3 on 2024-05-01 12:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("BranchesInfo", "0016_alter_data_records_receiver_branch_cd_and_more"),
        ("userManagement", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="data_records",
            name="Client_Id",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="client_orders",
                to="userManagement.client",
            ),
        ),
    ]
