# Generated by Django 5.0.3 on 2024-05-03 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("BranchesInfo", "0017_alter_data_records_client_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="chargedetails",
            name="Description",
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="chargedetails",
            name="Amount",
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name="chargedetails",
            name="Distance",
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name="chargedetails",
            name="Weight",
            field=models.BigIntegerField(),
        ),
    ]
