# Generated by Django 5.0.3 on 2024-05-03 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "BranchesInfo",
            "0018_chargedetails_description_alter_chargedetails_amount_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="chargedetails",
            name="Description",
            field=models.CharField(max_length=500, null=True),
        ),
    ]
