# Generated by Django 5.0.3 on 2024-05-03 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("BranchesInfo", "0019_alter_chargedetails_description"),
    ]

    operations = [
        migrations.AlterField(
            model_name="chargedetails",
            name="PlanCode",
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
