# Generated by Django 5.0.3 on 2024-05-05 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("BranchesInfo", "0022_data_records_distance"),
    ]

    operations = [
        migrations.AddField(
            model_name="delivery_boy_details",
            name="Number_Of_Alloted_Packets",
            field=models.IntegerField(max_length=400, null=True),
        ),
    ]
