# Generated by Django 5.0.3 on 2024-05-05 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("BranchesInfo", "0023_delivery_boy_details_number_of_alloted_packets"),
    ]

    operations = [
        migrations.AddField(
            model_name="data_records",
            name="Payment_Method",
            field=models.CharField(default="cash", max_length=50),
            preserve_default=False,
        ),
    ]
