# Generated by Django 5.0.3 on 2024-05-05 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("BranchesInfo", "0024_data_records_payment_method"),
    ]

    operations = [
        migrations.AlterField(
            model_name="delivery_boy_details",
            name="Number_Of_Alloted_Packets",
            field=models.IntegerField(null=True),
        ),
    ]
