# Generated by Django 5.0.3 on 2024-05-06 04:39

import BranchesInfo.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("BranchesInfo", "0025_alter_delivery_boy_details_number_of_alloted_packets"),
    ]

    operations = [
        migrations.CreateModel(
            name="Qr_Details",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("awbno", models.CharField(max_length=100)),
                (
                    "Qr_image",
                    models.ImageField(upload_to=BranchesInfo.models.qr_image_path),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
