# Generated by Django 5.0.3 on 2024-04-20 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Client",
            fields=[
                (
                    "Client_Id",
                    models.CharField(max_length=50, primary_key=True, serialize=False),
                ),
                ("Client_Name", models.CharField(max_length=100)),
                ("Client_Address", models.CharField(max_length=200)),
                ("Client_contact_N0", models.CharField(max_length=15, null=True)),
                ("Client_Email_Id", models.CharField(max_length=30, null=True)),
            ],
        ),
    ]
