# Generated by Django 5.0.3 on 2024-04-26 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Client",
            fields=[
                ("Client_Id", models.BigAutoField(primary_key=True, serialize=False)),
                ("Client_Name", models.CharField(max_length=100)),
                ("Client_Address", models.CharField(max_length=200)),
                ("Client_contact_No", models.CharField(max_length=15, null=True)),
                ("Client_Email_Id", models.CharField(max_length=30, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Login_Info",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("User_Id", models.CharField(max_length=50)),
                ("User_Password", models.CharField(max_length=20)),
                ("User_Type", models.CharField(max_length=7)),
            ],
        ),
    ]
