# Generated by Django 5.0.3 on 2024-04-22 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("userManagement", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Login_Info",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("User_Id", models.CharField(max_length=50)),
                ("User_Password", models.CharField(max_length=20)),
                ("User_Type", models.CharField(max_length=5)),
            ],
        ),
    ]
