# Generated by Django 5.0.3 on 2024-05-14 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("userManagement", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="client",
            name="Client_Email_Id",
            field=models.CharField(max_length=30, null=True, unique=True),
        ),
    ]
