# Generated by Django 5.0.3 on 2024-04-22 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("userManagement", "0003_rename_client_contact_n0_client_client_contact_no"),
    ]

    operations = [
        migrations.AlterField(
            model_name="login_info",
            name="User_Type",
            field=models.CharField(max_length=7),
        ),
    ]
