# Generated by Django 5.0.3 on 2024-04-22 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("userManagement", "0005_remove_login_info_id_alter_login_info_user_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="login_info",
            name="id",
            field=models.BigAutoField(
                auto_created=True,
                default=1,
                primary_key=True,
                serialize=False,
                verbose_name="ID",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="login_info",
            name="User_Id",
            field=models.CharField(max_length=50),
        ),
    ]
