# Generated by Django 5.0.3 on 2024-04-22 20:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("userManagement", "0006_login_info_id_alter_login_info_user_id"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Client",
        ),
    ]
