# Generated by Django 5.0.3 on 2024-04-22 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("userManagement", "0007_delete_client"),
    ]

    operations = [
        migrations.CreateModel(
            name="Client",
            fields=[
                (
                    "Client_Id",
                    models.CharField(max_length=50, primary_key=True, serialize=False),
                ),
                ("Client_Name", models.CharField(max_length=100)),
                ("Client_Address", models.CharField(max_length=200)),
                ("Client_contact_No", models.CharField(max_length=15, null=True)),
                ("Client_Email_Id", models.CharField(max_length=30, null=True)),
            ],
        ),
    ]
