# Generated by Django 5.0.3 on 2024-04-22 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("userManagement", "0008_client"),
    ]

    operations = [
        migrations.AlterField(
            model_name="client",
            name="Client_Id",
            field=models.BigAutoField(max_length=50, primary_key=True, serialize=False),
        ),
    ]
